add custom install info for terraform-provider-aws
paxosglobal/terraform-provider-aws pull request #155
Opened 2022-06-15 13:40 UTC by mike2194

add PAXOS_INSTALL.md

2022-06-15 14:09 UTC, dchernivetsky requested changes

2022-06-15 14:09 UTC, dchernivetsky commented on PAXOS_INSTALL.md
> +3. Create the local override: `mkdir -p ~/.terraform.d/plugins/paxos.com/paxos/aws/4.9.111/darwin_amd64`
i think we want to change paxos.com prefix no?

2022-06-15 14:24 UTC, dchernivetsky approved these changes

2022-06-15 14:24 UTC, merged

2022-12-09 17:24 UTC, Conshandacox1 reviewed
Request change

2022-12-09 17:25 UTC, Conshandacox1 reviewed
Request change